### ISSUE TITLE
Batching

### ISSUE THREAD

**Issue by pka** [alexpusch/pumps_rs#2]
I tried doing batching with the existing pumps, but got only almost there:

```rust
let batch = Arc::new(tokio::sync::Mutex::new(Batch::new(2)));
let (mut output, _h) = Pipeline::from_iter(vec![1, 2, 3, 4, 5])
    .filter_map(
        move |v| {
            let batch = batch.clone();
            async move { batch.lock().await.push(v).await }
        },
        Concurrency::concurrent_unordered(2),
    )
    .map(|x| async move { x }, Concurrency::serial())
    .build();
while let Some(output) = output.recv().await {
    println!("{output:?}");
}
```

`Batch::push` returns None, when the buffer is not full yet. So the last value gets lost. Output:
```
[1, 2]
[3, 4]
```

I think we need an additional `Pump` type for that. Maybe something like [batching](https://docs.rs/par-stream/latest/par_stream/prelude/trait.StreamExt.html#tymethod.batching) in [par-stream](https://docs.rs/par-stream)?

**Comment by alexpusch** [comment]
done in #4
